"""empty message

Revision ID: 1745fdb24b5b
Revises: c8e0442b4629
Create Date: 2024-03-05 00:02:18.034073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1745fdb24b5b'
down_revision = 'c8e0442b4629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.BLOB(), nullable=False))

    # ### end Alembic commands ###
