"""empty message

Revision ID: 37648f0bd51c
Revises: 05793ee5179d
Create Date: 2024-05-15 22:43:34.551088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37648f0bd51c'
down_revision = '05793ee5179d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
